---
- name: Install BIND9
  apt:
    name: bind9
    state: present
    update_cache: yes

- name: Install BIND9 utilities
  apt:
    name: bind9utils
    state: present

- name: Ensure BIND9 service is started and enabled
  service:
    name: bind9
    state: started
    enabled: yes

- name: Copy the named.conf file
  template:
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: '0644'

- name: Ensure the bind directory for zones exists
  file:
    path: /var/cache/bind
    state: directory
    owner: bind
    group: bind
    mode: '0755'
